### ISSUE TITLE
chrome

### ISSUE THREAD

**Issue by TrySound** [timdown/rangy-release#3]
macosx chrome
 'Attr.nodeValue' is deprecated. Please use 'value' instead.

**Comment by timdown** [comment]
Could you provide a little more context?

**Comment by TrySound** [comment]
https://github.com/timdown/rangy-release/blob/master/rangy-classapplier.js#L230
https://developer.mozilla.org/en-US/docs/Web/API/Attr

**Comment by timdown** [comment]
Thanks. I had guessed that's where it may be in the code. I was more hoping for a way to replicate the issue, but I'm sure I can work it out.

**Comment by timdown** [comment]
I've fixed the issue in the main Rangy repository.

**Comment by TrySound** [comment]
Thanks!
